// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyB95yRLVwGPUktnVEyZqXAHMdRyIiBPIec',
    appId: '1:435592608288:web:ea0e71151cdd0cebceda45',
    messagingSenderId: '435592608288',
    projectId: 'safekids-dc94d',
    authDomain: 'safekids-dc94d.firebaseapp.com',
    storageBucket: 'safekids-dc94d.appspot.com',
    measurementId: 'G-V5WZQD6379',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBWBreLNCFYc4qxqVvc-qondfLvy5q9C14',
    appId: '1:435592608288:android:f0ec5c5b001ce37fceda45',
    messagingSenderId: '435592608288',
    projectId: 'safekids-dc94d',
    storageBucket: 'safekids-dc94d.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCPqOdSjoqr2JXvJkKZNcVHQAC8U1uw8Zw',
    appId: '1:435592608288:ios:c58bef0b3bd075c0ceda45',
    messagingSenderId: '435592608288',
    projectId: 'safekids-dc94d',
    storageBucket: 'safekids-dc94d.appspot.com',
    iosBundleId: 'com.example.safekids',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCPqOdSjoqr2JXvJkKZNcVHQAC8U1uw8Zw',
    appId: '1:435592608288:ios:c58bef0b3bd075c0ceda45',
    messagingSenderId: '435592608288',
    projectId: 'safekids-dc94d',
    storageBucket: 'safekids-dc94d.appspot.com',
    iosBundleId: 'com.example.safekids',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyB95yRLVwGPUktnVEyZqXAHMdRyIiBPIec',
    appId: '1:435592608288:web:d0d5cd07e08e65ddceda45',
    messagingSenderId: '435592608288',
    projectId: 'safekids-dc94d',
    authDomain: 'safekids-dc94d.firebaseapp.com',
    storageBucket: 'safekids-dc94d.appspot.com',
    measurementId: 'G-RHZYKX5PDB',
  );
}
